Feat(book api) : 책 관련 api 추가
PoolC/Mincho pull request #69
Opened 2021-02-17 10:18 UTC by yoonseokch

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] 책 조회 api 구현
- [x] 책 대여 api 구현
- [x] 책 반납 api 구현
- [x] 책 삭제,등록,수정(관리자권한) api 구현
- [x] Test를 위한 BookDataLoader 생성 및 적용
- [x] BookAcceptanceTest 추가
- [x] jwt 인증을 위해 interceptor 추가   

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [x] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [x] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?
      <br/>

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- jwt token provider같은 경우 기존 jwt token provider 수정이 끝나지 않아서 맞춰서 변경할 예정입니다.
- Interceptor 같은 경우 path 추가를 해야하는데 현재는 각 package  내에 있는 infra에서 추가를 해주고 있으나 추후에 통합에서 관리할 예정입니다.
- package에 spring test가 추가되어 있는데 dirtiescontext를 사용할 예정입니다. 곧 커밋하겠습니다

<br/><br/>

2021-02-17 10:20 UTC, yoonseokch commented on src/main/java/org/poolc/api/member/domain/Member.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
이 annotation은 jsonCreator에서 json으로 변환할때 나오는 에러를 해결하기 위해 추가하였습니다.
관련 내용은 [링크](https://stackoverflow.com/questions/4486787/jackson-with-json-unrecognized-field-not-marked-as-ignorable)를 참조하였습니다.

2021-02-18 06:53 UTC, hcpak requested changes

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
```json
{
	data:[
		{
			id,
			title,
			author,
			imageURL,
			status,
			
		}
	]
}
```
저희 api 명세에 다음과 같이 되어 있어서, "data" 키값에 리스트가 들어가도록 만들어야 할 거 같습니다.
![스크린샷 2021-02-18 오후 3 16 19](https://user-images.githubusercontent.com/68177113/108313839-4946b500-71fc-11eb-94a4-a47d7ceff362.png)

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
> 이거 제가 작성했네요? 😂
> 
> 존재하지 않는 회원을 삭제하려고 하는거니까 괜찮다의 의미를 내포하는 2XX 상태코드보단 4XX (아마도 Bad request가 제일 맞을 것 같은데) 류의 상태코드를 기대하는게 더 맞을 것 같아요. 너무 예시코드를 맹신하진 말아주세요....

이것과 비슷한 사례로 다음과 같은 리뷰( https://github.com/PoolC/poolc-renewal-back/pull/68#discussion_r576960684 ) 를 받은 적이 있는데, 저는 http 상태 코드를 BAD_REQUEST로 보냈습니다.

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/service/BookService.java
> +        }
saveBook와 updateBook 분에서 이 로직을 쓰는데 따로 메소드를 만드는 게 좋을 거 같습니다. Duplicate에 관련된 Exception을 만들어주는 것도 좋을 거 같아요.

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/service/BookService.java
>  @Transactional(readOnly = true)
> private 또는 protected으로 선언된 메소드들을 되도록이면 가장 아래로 옮겨주세요

저도 비슷하게 하다가 다음과 같은 리뷰를 받았습니다. https://github.com/PoolC/poolc-renewal-back/pull/68#discussion_r576935083

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/service/BookService.java
>      }
혹시 service에서 생성,수정,삭제하는 것은 @Transactional을 붙여야 하나요? 안 붙인다면 어떤 에러가 발생했나요?

2021-02-18 06:53 UTC, hcpak commented on src/main/java/org/poolc/api/book/infra/BearerAuthInterceptor.java
> +        }
https://github.com/PoolC/poolc-renewal-back/pull/68#discussion_r576986338 의 2번 때문에 작성하신건가요?

2021-02-18 09:22 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
수정하도록 하겠습니다!

2021-02-18 09:22 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
수정하도록 하겠습니다!

2021-02-18 09:24 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/service/BookService.java
>      }
transacational을 안붙이면 중간에 에러가 났을때 기존에 실행했던 로직이 rollback이 되지않습니다 예를 들면 book 을 unavailable로 바꾸고 borrower를 member로 바꾸려는데 존재하지 않는 멤버같은 에러가 뜨면 status가 rollback이 되지 않습니다 @transacational을 붙이면 하나의 메쏘드를 하나의 트랜잭션 안에서 처리합니다

2021-02-18 09:25 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/infra/BearerAuthInterceptor.java
> +        }
Interceptor에서 error handler를 적용할수 없기에 exception page로 이동시켜 주었습니다. jwtTokenProvider의 경우 main branch에 맞게 수정하도록 하겠습니다

2021-02-18 09:41 UTC, hcpak commented on src/main/java/org/poolc/api/book/service/BookService.java
>      }
오 설명 감사합니다. 저도 그 부분에 대해서 수정해야할 거 같습니다.

2021-02-18 09:55 UTC, hcpak commented on src/main/java/org/poolc/api/book/infra/BearerAuthInterceptor.java
> +        }
오 그렇다면 토큰이 유효하지 않을 경우에 바로 /error로 이 페이지로 이동하는 건가요??

생각해보니 인증 정보가 잘못된 거에 대한 에러 처리가 없었네요. 수고하셨습니다.

2021-02-18 11:29 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
근데 멤버쪽도 data 안에 들어가는 명세로 되어있는데  member 쪽은 그냥 list로 반환하지 않나요?

2021-02-18 11:44 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/controller/BookController.java
> +    }
수정하였습니다!

2021-02-18 11:57 UTC, yoonseokch commented on src/main/java/org/poolc/api/book/service/BookService.java
> +        }
해결하였습니다!

2021-02-19 03:35 UTC, hcpak approved these changes
수고하셨습니다!

2021-02-19 03:35 UTC, merged